# Generated by Django 4.1.3 on 2022-11-16 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Departure",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=50)),
                ("departure_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=50)),
                ("arrival_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateTimeField()),
                (
                    "departure_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="departures",
                        to="accounts.departure",
                    ),
                ),
                (
                    "destination_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="destinations",
                        to="accounts.destination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("seat_class", models.CharField(max_length=50)),
                ("seat", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "trip_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trip",
                        to="accounts.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("serial_number", models.UUIDField(default=uuid.uuid4)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "ticket_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ticket_types",
                        to="accounts.tickettype",
                    ),
                ),
                (
                    "trip_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="trips",
                        to="accounts.trip",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="tickets",
                        to="accounts.ticket",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
