# Generated by Django 4.1.3 on 2022-11-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_ticket_ticket_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettype",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
