# Generated by Django 4.1.3 on 2022-11-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_tickettype_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="ticket_type_id",
            new_name="ticket_type",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="trip_id",
            new_name="trip",
        ),
        migrations.RenameField(
            model_name="tickettype",
            old_name="trip_id",
            new_name="trip",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="departure_id",
            new_name="departure",
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="destination_id",
            new_name="destination",
        ),
    ]
