# Generated by Django 4.1.3 on 2022-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_ticket_id_booking_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
