# Generated by Django 4.1.3 on 2022-12-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_tickettype_seat_ticket_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="arrival_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="trip",
            name="departure_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Departure",
        ),
        migrations.DeleteModel(
            name="Destination",
        ),
    ]
