# Generated by Django 4.1.3 on 2022-12-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_tickettype_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tickettype",
            name="seats",
        ),
        migrations.AddField(
            model_name="trip",
            name="seats",
            field=models.IntegerField(default=20),
        ),
    ]
