# Generated by Django 4.1.3 on 2022-12-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_tickettype_seats_trip_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickettype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
